### ISSUE TITLE
only ratter is hackergod and his friend ( ion fn owner )

### ISSUE THREAD

**Issue by xenos1337** [LimeGroupYT/covid-69-SOURCE-FIXED#1]
**i think you made an mistake who the ratter and token logger is oof just sad...**

![image](https://user-images.githubusercontent.com/66328734/93804772-10071a80-fc47-11ea-8769-e4930369cda2.png)
![image](https://user-images.githubusercontent.com/66328734/93804782-11d0de00-fc47-11ea-83a4-9d7b0763a5a0.png)
![image](https://user-images.githubusercontent.com/66328734/93804784-139aa180-fc47-11ea-9db3-4ab06dfae14f.png)
![image](https://user-images.githubusercontent.com/66328734/93804793-14cbce80-fc47-11ea-9934-a6665871afe8.png)
![image](https://user-images.githubusercontent.com/66328734/93804799-172e2880-fc47-11ea-91af-01f93134410f.png)
![image](https://user-images.githubusercontent.com/66328734/93804839-290fcb80-fc47-11ea-81f2-a394bfb7bfe2.png)
![image](https://user-images.githubusercontent.com/66328734/93804852-2ad98f00-fc47-11ea-931a-7946864c266a.png)

**Comment by KubaMorinkton** [comment]
<3

**Comment by ytmcgamer** [comment]
same

**Comment by ytmcgamer** [comment]
Still no respone from this guy sad 😂🤡 skids

**Comment by ytmcgamer** [comment]
e

**Comment by ytmcgamer** [comment]
🤡

**Comment by ytmcgamer** [comment]
can i get an respond clowns

**Comment by ytmcgamer** [comment]
respond clowns

**Comment by IvanBMWorld** [comment]
lol
